// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

//import "dotenv/config";
//changed to code bellow because dotenv defaults to using .env insted of .env.local file i already had
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import { defineConfig } from "prisma/config";

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL is not defined in .env.local");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});